import { ApiProperty } from '@nestjs/swagger';
import { Tenant } from '@workspace/database';

export class TenantEntity implements Tenant {
  /*
  this code was not generated by prisma-generator-nestjs-dto
  but manually added to demonstrate usage of decorators along with @nestjs/swagger Exluce/Expose Properties
  the reason to implement an entity like this, is to be able to exlude certain properties from the response 
  and to document it accordingly with the @nestjs/swagger @ApiReponse decorators
  e.g. password fields, createdAt, updatedAt, etc.
  an example is found in this prisma-nestjs documentation: https://www.prisma.io/blog/nestjs-prisma-relational-data-7D056s1kOabc#generate-new-users-rest-resource
  */
  constructor(partial: Partial<TenantEntity>) {
    Object.assign(this, partial);
  }

  @ApiProperty({
    type: 'string',
  })
  tenantId: string;
  @ApiProperty({
    description: 'Subdomain of the tenant',
    minimum: 5,
    type: 'string',
    nullable: false,
  })
  subdomain: string;
  @ApiProperty({
    description: 'Database URL of the tenant',
    minimum: 5,
    type: 'string',
    nullable: true,
  })
  dbUrl: string;
  @ApiProperty({
    description: 'Description of the tenant',
    type: 'string',
    required: false,
    nullable: true,
  })
  description: string | null;
  @ApiProperty({
    description: 'Company name of the tenant',
    type: 'string',
    required: true,
    nullable: true,
  })
  companyName: string;
  @ApiProperty({
    description: 'Creation date of the tenant',
    type: 'string',
    required: false,
    nullable: true,
  })
  createdAt: Date;
  @ApiProperty({
    description: 'Last updated date of the tenant',
    type: 'string',
    required: false,
    nullable: true,
  })
  updatedAt: Date;
  @ApiProperty({
    description: 'ID of the address associated with the tenant',
    type: 'string',
    required: false,
    nullable: false,
  })
  addressId: string;
  @ApiProperty({
    description: 'Indicates if the tenant is configured',
    type: 'boolean',
    required: false,
    nullable: true,
  })
  isConfigured: boolean;
  @ApiProperty({
    description: 'Indicates if the tenant is deleted',
    type: 'boolean',
    required: false,
    nullable: false,
  })
  deleted: boolean;
}
